#!/usr/bin/env python3
"""Compress a linked payload and emit it as a C array for the loader stub.

The shipped .bin is a small self-extracting stub with the compressed image
trailing it, because TegraRcmSmash - which TegraRcmGUI drives - prepends a
fixed 66216-byte exploit prologue and then truncates the whole buffer to
192 KiB without reporting anything. Payloads past 130392 bytes are silently
cut off and the console jumps into a partial image.

The codec is the BCL LZ77 that BDK already carries as LZ_Uncompress(), so the
on-device side is hekate's decompressor; only the packer lives here. It is
imported from the injector, which has been round-tripping the same format
over the wire for a while.

    mkpayload.py <payload.bin> <out.lz> <out.h>
"""
import os
import sys

# The packer sits alongside this script. It must not be imported from a
# sibling checkout: CI builds this repository alone.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import lzpack


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: mkpayload.py <payload.bin> <out.lz> <out.h>")

    raw_path, lz_path, h_path = sys.argv[1:4]
    raw = open(raw_path, "rb").read()
    packed = lzpack.compress(raw)

    # Refuse to ship something that would not survive the round trip: a
    # corrupted payload would fail as a hang on a repair tech's console, with
    # nothing on screen to say why.
    if lzpack.decompress(packed) != raw:
        sys.exit("mkpayload: compressed image does not round-trip")

    open(lz_path, "wb").write(packed)

    with open(h_path, "w", newline="\n") as f:
        f.write("/* generated by tools/mkpayload.py - do not edit */\n")
        f.write("static const unsigned char "
                "__attribute__((section(\"._payload_lz\"))) payload_lz[] = {\n")
        for i in range(0, len(packed), 16):
            f.write("".join("0x%02X," % b for b in packed[i:i + 16]) + "\n")
        f.write("};\n")

    print("  packed %d -> %d bytes (%.1f%%)"
          % (len(raw), len(packed), 100.0 * len(packed) / len(raw)))


if __name__ == "__main__":
    main()
